# Generated by Django 2.0.2 on 2018-02-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Designation')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
                ('joined_at', models.DateField(verbose_name='Joined At')),
                ('leaved_at', models.DateField(verbose_name='Leaved At')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_management.Designation', verbose_name='Designation')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('desc', models.TextField(db_column='description', verbose_name='Description')),
                ('start_from', models.DateField(verbose_name='Start From')),
                ('end_at', models.DateField(blank=True, null=True, verbose_name='End At')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_management.Organization', verbose_name='Developed At')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.ManyToManyField(to='portfolio_management.Role', verbose_name='Role'),
        ),
    ]
